---
# dependency:
#   name: galaxy
dependency:
  name: galaxy
driver:
  name: google.cloud.gcp_compute_instance
lint: |
   yamllint
platforms:
  - name: instance-travis
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1804    #-xenial #-v20170919
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: testinfra
  lint: |
    flake8